### ISSUE TITLE
PRÁCTICA_LÓPEZ_DOMÍNGUEZ_ISAÍAS_BRAYAN

### ISSUE THREAD

**Issue by 23620031** [SistemasTecTlaxiaco/actividad-6-practica-de-relaciones-equipo-isaias-paola-ariadna-arisbeth#1]
[PRÁCTICA_LÓPEZ_DOMÍNGUEZ.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-relaciones-equipo-isaias-paola-ariadna-arisbeth/files/12810178/PRACTICA_LOPEZ_DOMINGUEZ.pdf)

**Comment by Felix-Angel** [comment]
Portada: 25%
Procedimiento: 25%
Ilustraciones, figuras y fotografías: 22% (Enlisto menos de 10 figuras)
Resultados y conclusiones: 25%
Total: 19.4/20
Evaluó equipo de Diego, Daniel, Félix Y Mayra.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
