### ISSUE TITLE
Practica U2

### ISSUE THREAD

**Issue by Paola939** [SistemasTecTlaxiaco/actividad-6-practica-de-relaciones-equipo-isaias-paola-ariadna-arisbeth#2]
[PracticaU2.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-relaciones-equipo-isaias-paola-ariadna-arisbeth/files/12812689/PracticaU2.pdf)

**Comment by DanAlejandr** [comment]
Portada: 25%
Procedimiento: 25%
Figuras, ilustraciones y Fotografías: 25%
Resultados y Conclusión: 25%
Total 20/20
Evaluó equipo de Diego, Daniel, Félix Y Mayra.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
